### ISSUE TITLE
suggestions for uncovered topics

### ISSUE THREAD

**Issue by ozza** [ankurk91/laravel-socialite-multiple-providers-example#1]
hello,

first, thank you for your application. it was a great tutorial for me.

i'd like to ask some suggestions about connecting and disconnecting social accounts into one account. i'm making a web site which users can register only using social accounts, no email registrations. and i also want users can use multiple social accounts like facebook and twitter. it confuses me a lot. can you suggest me a way for achieving this?

thanks.

**Comment by ankurk91** [comment]
To disable normal registrations, you can just disable everything related to Laravel's inbuilt registration feature, controller, routes etc.

My current implementation of socialite can handle multiple social accounts already for a user.

You just need to build a disconnect feature where you can disconnect from social account but they need to use regular login afterwards.
To disconnect, you can just delete reference from social_accounts table.

**Comment by ozza** [comment]
thank you for your suggestions.
